name: project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.5.1
  provider: ^4.0.1
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/stonefree.png
    - assets/crazydiamond.png
    - assets/aerosmith.png
    - assets/goldexperience.png
    - assets/heavensdoor.png
    - assets/killerqueen.png
    - assets/spicegirl.png
    - assets/weatherreport.png
    - assets/stickyfingers.png
    - assets/sexpistols.png
    - assets/stands.json    
    - assets/StatTriangle.png    