name: project
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.5
  provider: ^3.2.0
  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.12.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/stonefree.png
    - assets/crazydiamond.png
    - assets/aerosmith.png
    - assets/stands.json