name: exemples
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.4.5
  cupertino_icons: ^0.1.2
  provider: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/stonefree.png
    - assets/crazydiamond.png
    - assets/aerosmith.png
    - assets/stands.json
